### ISSUE TITLE
403 Forbidden on any auth'ed request

### ISSUE THREAD

**Issue by TheChrisTech** [tg44/nicehash-exporter#3]
Hi,

I just started getting 403 Forbidden for any request that requires authentication. I've attached my docker logs to this ticket. Not sure if it's something that the authentication is wrong or I'm blocked by Cloudflare (I see some reference in the logs).

[nicehashexporter.txt](https://github.com/tg44/nicehash-exporter/files/6673955/nicehashexporter.txt)

Essentially, I'd like to know if anyone else is having this issue, or if it's just me.

Thanks!

**Comment by tg44** [comment]
I started to see that something off at me too, but I had no time to check it. Probably tomorrow I will have some time to play with it, and find the problem.

**Comment by tg44** [comment]
I just pushed a fix, I think some things are changed at the NH side, and they made the orgId mandatory. I added it as an env + propagate it as header too, it works for me!
