### ISSUE TITLE
Prometheus and data over periods of time

### ISSUE THREAD

**Issue by TheChrisTech** [tg44/nicehash-exporter#4]
Hello,

I'm having issues with getting this data to be represented in Grafana properly, but I'm starting to think it's a Prometheus thing. When data is recorded, eg. if I mine for 5 minutes with a 3090, stop, and continue to graph data (even query in Prometheus), it'll continue to "extend" that value over the next few hours. I need to write some crazy queries that look up a devices current mining status to show it or not:

`nh_device_power{rig_name=~"$rig", device_type!="CPU", device_name=~"$device"} + on(device_id, device_name) nh_device_status_info{status="MINING"}-1`

Am I doing something stupid? I don't think other databases have an issue like this, and I'm tempted to port this to something else (like InfluxDB), but that's where my knowledge of the Nicehash API, and it's crazy requirements for nonce and stuff come in. Any tips?

**Comment by tg44** [comment]
What do you exactly want to achive? my most complex graph is
`(sum(nh_total_btc) + sum(nh_unpaid_amount))*(sum(nh_btc_usd_rate OR clamp_max(absent(nh_btc_usd_rate),0))+sum(nh_btcusdc_rate OR clamp_max(absent(nh_btcusdc_rate),0)))` 
combined with the power usage iot sensors data to show actual profit.

Otherwise, I simply use `nh_device_speed` and `nh_devices_statuses`. When something is strange these are good indicators (for me at least).

**Comment by TheChrisTech** [comment]
Here's an example. I own one 3060 card. It obviously can't be mining all of these algo's at once.
![image](https://user-images.githubusercontent.com/32913587/129972498-9824d50d-c6ca-4ed1-9c03-f57eb1b37118.png)

**Comment by tg44** [comment]
<img width="560" alt="image" src="https://user-images.githubusercontent.com/31839/130093842-7e02342a-c730-45e1-9359-c7b02357e315.png">

Without any magic, my 3 cards shows the good values. Even if I go back in time, I only get "duplicates" bcs my rig was detected as a new. Try to leaving out the on-group_left-statusinfo part.

It is a possible scenario that when a card changes from A algo to B we keep the A value, and report it. Can you confirm that?
(call the reporters /metrics endpoint, and check if it has multiple nh_device_speed rows in it (with value))

https://github.com/tg44/nicehash-exporter/blob/main/app.js#L146 before this line we probably should reset all the labels for this metric... I try to fix this up today.

**Comment by tg44** [comment]
Probably thats it, I just pushed a fix, I hope this will solve it! (https://github.com/tg44/nicehash-exporter/commit/cfa5544ea10a67e0e561a110944eb0339fed6dcb)

**Comment by TheChrisTech** [comment]
@tg44 - You are awesome. I just applied it and my Algo chart is working as expected. This will probably fix my other issues with charts as well :) This is amazing.

Also, thoughts on adding Grafana dashboard JSON to this repo? Might help others get started.

**Comment by tg44** [comment]
Yeah, I had the idea once to do this, then I realized that I heavily use my actual power consumption on the graphs, and probably that is not really general. All of my other graphs are basically just plot the metrics kind of stuff...

If you have a good dashboard you can share with us, but I close this issue bcs I fixed it :)
