### ISSUE TITLE
Version of miner software

### ISSUE THREAD

**Issue by manustars** [tg44/nicehash-exporter#5]
congratulations for the tool, I have a small request, is it possible to also enter the version of the miner running the worker in the deviceStatusInfo? or on another tab that still has the rigname field

**Comment by tg44** [comment]
Hy!

I'm not a nicehash user from a while. The problem with the versions are that they are string and not a number if I remember well, so they will be never as good as a standard quantity like the temperature. I could guide you how this could be done, if you interested to work on it and test and PR it yourself.

**Comment by manustars** [comment]
I'm interested but I state that I'm not a developer :). i don't know if it can be useful, the results of devicestatusinfo are not numerical but they are strings. In the json block extracted from the api (where the rigname, rigid, minerstatus is already taken) there is the value related to "sofwareVersion"

`const deviceStatusInfo = new Gauge({
  name: prefix +'device_status_info',
  help: 'deviceStatusInfo',
  labelNames: ['rig_name', 'device_name', 'device_id', 'device_type', 'status'],
});`

**Comment by manustars** [comment]
I make it simplistic given my inexperience in development
this the code original (without software version)
```
LINE 112 --- const deviceStatusInfo = new Gauge({ name: prefix +'device_status_info', help: 'deviceStatusInfo', labelNames: ['rig_name', 'device_name', 'device_id', 'device_type', 'status'], });

LINE 149 --- deviceStatusInfo.labels(rig.name, device.name, device.id, device.deviceType.enumName, device.status.enumName).set(1)
```

this the code with sofTware version (the changes in bold):

```
LINE 112 --- const deviceStatusInfo = new Gauge({ name: prefix +'device_status_info', help: 'deviceStatusInfo', labelNames: ['rig_name', **'rig_softwareversions'**, 'device_name', 'device_id', 'device_type', 'status'], });

LINE 149 --- deviceStatusInfo.labels(rig.name, **rig.softwareVersions**, device.name, device.id, device.deviceType.enumName, device.status.enumName).set(1)
```

**Comment by manustars** [comment]
this in fantastic.

I don't know exactly where the patching should be done and how it should be updated in the docker image :(

**Comment by manustars** [comment]
I'm sorry, but then you managed to implement that parameter?

**Comment by tg44** [comment]
Sorry, I had busy weeks. ca297d1 should solve this, try to `docker pull ghcr.io/tg44/nicehash-exporter:latest` and restart the container, I did not tested this, if its not working, you can revert back to `ghcr.io/tg44/nicehash-exporter:sha-cfa5544`

**Comment by manustars** [comment]
its fantastic 
![image](https://github.com/tg44/nicehash-exporter/assets/60410607/6757fcd2-0996-4c9c-935f-c83652a66616)

**Comment by tg44** [comment]
Thanks the testing, I close this!
